<expr> ::= "("<arith_expr> <expr> <expr>")" | "("<if_expr> <bool_expr> <expr> <expr>")" | <var>
<arith_expr>  ::= + | - | * | /
<bool_expr> ::=  "(<" <expr> <expr>")" | "(>" <expr> <expr>")"
<if_expr>  ::= if
<var>  ::= x0 | 1.0